services:
  - type: web
    name: archivewrapped
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 2 --timeout 300 --bind 0.0.0.0:$PORT --max-requests 100 --max-requests-jitter 10 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 1
      - key: MPLCONFIGDIR
        value: /tmp/matplotlib
